###
GET http://localhost:13000/api/
###

### USERS ENDPOINTS

###  fetch the logged in user
GET http://localhost:13000/api/users/
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6MX0sImlhdCI6MTcyNTIxNzk5MH0.QgJL0jGKfKxnf2HRI5UuxELSg6KO2GJ5n3JmCuwJlGA
###

### signup
POST http://localhost:13000/api/users/signup
Content-Type: application/json

{
    "username": "hassan",
    "email": "hassan@owu.edu",
    "password": "Sufian135?"
}
###

### login
POST http://localhost:13000/api/users/login
Content-Type: application/json

{
    "username": "hhmushtaq",
    "password": "Sufian135?"
}

### Update level
PATCH http://localhost:13000/api/users/
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6MX0sImlhdCI6MTcyNTIxODU2MX0._dLs2zg8CU5KHybvIYBnTIx-KBkJo0BjnkWJltIFxGI
Content-Type: application/json

{
    "xpGained": 50
}

### TASKS ENDPOINTS

### for dev
GET http://localhost:13000/api/tasks/all
###

### Fetch all tasks
GET http://localhost:13000/api/tasks/
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6MX0sImlhdCI6MTcyNTIxODU2MX0._dLs2zg8CU5KHybvIYBnTIx-KBkJo0BjnkWJltIFxGI
###

### Add a task
POST http://localhost:13000/api/tasks/
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6MX0sImlhdCI6MTcyNTIxODU2MX0._dLs2zg8CU5KHybvIYBnTIx-KBkJo0BjnkWJltIFxGI
Content-Type: application/json

{
    "description": "Task 2",
    "xpValue": 50
}
###

### Delete a task
DELETE http://localhost:13000/api/tasks/6
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6MX0sImlhdCI6MTcyNTIxODU2MX0._dLs2zg8CU5KHybvIYBnTIx-KBkJo0BjnkWJltIFxGI
###

### Update task
PATCH http://localhost:13000/api/tasks/12
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6MX0sImlhdCI6MTcyNTIxODU2MX0._dLs2zg8CU5KHybvIYBnTIx-KBkJo0BjnkWJltIFxGI
Content-Type: application/json

{
    "xpValue": 200,
    "completed": true,
    "description": "Changed"
}
###


