###
GET http://localhost:13000/api/
###

### AUTH ENDPOINTS

### for dev
GET http://localhost:13000/api/auth/
###

### signup
POST http://localhost:13000/api/auth/signup
Content-Type: application/json

{
    "username": "hassanmushtak",
    "email": "hassanmushtaq67@gmail.com",
    "password": "Sufian135?"
}
###

### login
POST http://localhost:13000/api/auth/login
Content-Type: application/json

{
    "username": "hhmushtaq",
    "password": "Sufian135?"
}

### TASKS ENDPOINTS


### for dev
GET http://localhost:13000/api/tasks/all
###

### Fetch all tasks
GET http://localhost:13000/api/tasks/
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6MX0sImlhdCI6MTcyNDk5MDc2NH0.-zNF2V3RIAk3KJVWNxEDpmk-UwmFqHmxbIPQYLqT9V8
###

### Add a task
POST http://localhost:13000/api/tasks/
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6MX0sImlhdCI6MTcyNDk5MDc2NH0.-zNF2V3RIAk3KJVWNxEDpmk-UwmFqHmxbIPQYLqT9V8
Content-Type: application/json

{
    "description": "Task 1",
    "xpValue": 50
}
###


### Delete a task
DELETE http://localhost:13000/api/tasks/11
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6MX0sImlhdCI6MTcyNDk5MDc2NH0.-zNF2V3RIAk3KJVWNxEDpmk-UwmFqHmxbIPQYLqT9V8
###

### Update task
PATCH http://localhost:13000/api/tasks/12
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6MX0sImlhdCI6MTcyNDk5MDc2NH0.-zNF2V3RIAk3KJVWNxEDpmk-UwmFqHmxbIPQYLqT9V8
Content-Type: application/json

{
    "xpValue": 200,
    "completed": true,
    "description": "Changed"
}
###